#!/usr/bin/env bash
#
# aws_segment

# shellcheck disable=SC2154
PL_OPTIONS[aws_symbol]=${PL_OPTIONS[aws_symbol]:-'☁ '}

# -----------------------------------------------------------------------------
# segment content: aws profile name
# shellcheck disable=SC2034
function _aws_segment {
    [[ -z ${AWS_PROFILE:-} ]] && return
    local -n _content="${1:-}"
    _content="${PL_OPTIONS[aws_symbol]}${AWS_PROFILE}"
}
