#!/bin/env bash
#
# aws_profile_segment

PL_SYMBOLS+=(
    # GUI Font Symbols      # Standard Symbols for tty
    [aws_profile]='☁'       [tty_aws_profile]='A'
)

# -----------------------------------------------------------------------------
# append to prompt: aws profile name
# arg: $1 foreground color
# arg; $2 background color
function aws_profile_segment {
    if [[ -n $AWS_PROFILE ]]; then
        local aws_profile_name="${AWS_PROFILE}"
        local bg_color="$1"
        local fg_color="$2"
        local content
        content=" $(pl_symbol 'aws_profile') $aws_profile_name"
        PS1+="$(segment_end "$fg_color" "$bg_color")"
        PS1+="$(segment_content "$fg_color" "$bg_color" "$content ")"
        # shellcheck disable=SC2034
        __last_color="$bg_color"    # variable will be used when sourced
    fi
}
