#!/bin/env bash

# battery_segment

PL_SYMBOLS+=(
    # GUI Font Symbols      # Standard Symbols for tty
    [battery_charge]="⚡"   [tty_battery_charge]="■"
    [battery_discharge]="▮" [tty_battery_discharge]="▬"
)

# -----------------------------------------------------------------------------
# append to prompt: indicator for battery level
# arg: $1 foreground color
# arg; $2 background color
function battery_segment {
    local bg_color="$1"
    local fg_color="$2"
    local batt_dir
    local content
    local batt_dir="/sys/class/power_supply/BAT"

    if [ -d $batt_dir"0" ]; then
        batt_dir=$batt_dir"0"
    elif [ -d $batt_dir"1" ]; then
        batt_dir=$batt_dir"1"
    else
        return 1
    fi

    local capacity
    capacity="$(<"$batt_dir/capacity")"
    local status
    status="$(<"$batt_dir/status")"
    local battery_symbol
    if [[ $status == "Discharging" ]]; then
        pl_symbol battery_symbol 'battery_discharge'
    else
        pl_symbol battery_symbol 'battery_charge'
    fi
    content="$battery_symbol$capacity%"

    PS1+="$(segment_end "$fg_color" "$bg_color")"
    PS1+="$(segment_content "$fg_color" "$bg_color" " $content ")"
    # shellcheck disable=SC2034
    __last_color="$bg_color"    # variable will be used when sourced
}
