#!/usr/bin/env bash

# battery_segment

# shellcheck disable=SC2154
PL_SYMBOLS[charge]=${PL_SYMBOLS[charge]:-'⚡'}
PL_SYMBOLS[discharge]=${PL_SYMBOLS[discharge]:-'▮'}
PL_OPTIONS[battery_threshold]=${PL_OPTIONS[battery_threshold]:-15}

# -----------------------------------------------------------------------------
# segment content: indicator for battery level
# shellcheck disable=SC2034
function _battery_segment {
    local -n _content="${1:-}"
    local -n _hilite="${2:-false}"

    local batt_dir="/sys/class/power_supply/BAT"
    if [[ -d "${batt_dir}0" ]]; then
        batt_dir="${batt_dir}0"
    elif [[ -d "${batt_dir}1" ]]; then
        batt_dir="${batt_dir}1"
    else
        return 1
    fi

    local capacity
    capacity="$(<"${batt_dir}/capacity")"
    local status
    status="$(<"${batt_dir}/status")"

    if [[ ${status} == "Discharging" ]]; then
        _content="${PL_SYMBOLS[discharge]}"
    else
        _content="${PL_SYMBOLS[charge]}"
    fi
    _content+="${capacity}%"
    [[ ${capacity} -lt ${PL_OPTIONS[battery_threshold]} ]] && _hilite=true
}
