#!/usr/bin/env bash

# battery_segment

PL_CHARGE_SYMBOL='⚡'
PL_DISCHARGE_SYMBOL='▮'

# -----------------------------------------------------------------------------
# append to prompt: indicator for battery level
# arg: $1 primary color
# arg: $2 secondary color
function battery_segment {
    local primary_color="$1"
    local secondary_color="$2"

    local batt_dir="/sys/class/power_supply/BAT"
    if [[ -d "${batt_dir}0" ]]; then
        batt_dir="${batt_dir}0"
    elif [[ -d "${batt_dir}1" ]]; then
        batt_dir="${batt_dir}1"
    else
        return 1
    fi

    local capacity
    capacity="$(<"${batt_dir}/capacity")"
    local status
    status="$(<"${batt_dir}/status")"

    local content
    if [[ ${status} == "Discharging" ]]; then
        content="${PL_DISCHARGE_SYMBOL}"
    else
        content="${PL_CHARGE_SYMBOL}"
    fi
    content+="${capacity}%"
    add_segment "${content}" "${primary_color}" "${secondary_color}"
}
