#!/bash/env bash

# conda_env_segment

PL_SYMBOLS+=( [python]='π')

# -----------------------------------------------------------------------------
# append to prompt: conda virtual environment name
# arg: $1 foreground color
# arg; $2 background color
function conda_env_segment {
    if [[ $CONDA_SHLVL -ne 0 && -n $CONDA_DEFAULT_ENV ]]; then
        local venv="${CONDA_DEFAULT_ENV##*/}"
        local bg_color="$1"
        local fg_color="$2"
        local content conda_symbol
        pl_symbol conda_symbol 'python'
        content="$conda_symbol $venv"
        local end_symbol
        segment_end end_symbol "$fg_color" "$bg_color"
        segment_content content "$fg_color" "$bg_color"
        PS1+="$end_symbol $content"
        # shellcheck disable=SC2034
        __last_color="$bg_color"    # variable will be used when sourced
    fi
}
