#!/usr/bin/env bash
#
# conda_segment

# shellcheck disable=SC2154
PL_SYMBOLS[conda]=${PL_SYMBOLS[conda]:-'π '}

# -----------------------------------------------------------------------------
# segment content: conda virtual environment name
# shellcheck disable=SC2034
function _conda_segment {
    local -n _content="${1:-}"


    if [[ ${CONDA_SHLVL:-} -ne 0 && -n ${CONDA_DEFAULT_ENV:-} ]]; then
        local venv="${CONDA_DEFAULT_ENV##*/}"
        _content="${PL_SYMBOLS[conda]}${venv}"
    fi
}
