#!/usr/bin/env bash

# kubernetes_segment

PL_SYMBOLS['kubernetes']=${PL_SYMBOLS[kubernetes]:-'\xE2\x8E\x88'}

# -----------------------------------------------------------------------------
# segment content:: default kubernetes context/namespace from $KUBECONFIG
# shellcheck disable=SC2034
function _kubernetes_segment {
    command -v kubectl &> /dev/null  || return # exit early if no kubectl

    local -n _content="${1:-}"
    local context
    context=$(kubectl config current-context)
    if [[ -n ${context} ]]; then
        local ns
        ns=$(kubectl config view -o jsonpath="{.contexts[?(@.name == \"${context}\")].context.namespace}")
        if [[ -n ${ns} ]]; then
            _content="${PL_SYMBOLS[kubernetes]} ${context}:${ns}"
        fi
    fi
}
