#!/bin/env bash

# kubernetes_segment

# -----------------------------------------------------------------------------
# append to prompt: default kubernetes context/namespace from $KUBECONFIG
# arg: $1 foreground color
# arg; $2 background color
function kubernetes_segment {
    # check if the 'kubectl' command is available
    if kubectl_loc="$(type -p "kubectl")" || [[ -n $kubectl_loc  ]]; then
        local context
        context=$(kubectl config current-context)
        if [ -n "$context"  ]; then
            local ns
            ns=$( kubectl config view -o jsonpath="{.contexts[?(@.name == \"${context}\")].context.namespace}"  )
            if [ -n "$ns"  ]; then
                local kubesymbol=$'\xE2\x8E\x88'
                local content="${kubesymbol} ${context}:${ns}"
                PS1+=$(segment_end "$1")
                PS1+=$(segment_content "$2" "$1" " $content ")
                # shellcheck disable=SC2034
                __last_color="$1"    # variable will be used when sourced
            fi
        fi
    fi

}
