#!/usr/bin/env bash
#
# prompt_segment

# shellcheck disable=SC2154
PL_OPTIONS[prompt_symbol_normal]=${PL_OPTIONS[prompt_symbol_normal]:-'\$'}
PL_OPTIONS[prompt_symbol_root]=${PL_OPTIONS[prompt_symbol_root]:-'#'}

# -----------------------------------------------------------------------------
# append to prompt: default is '$' for normal user and '#' for root
# shellcheck disable=SC2034
function _prompt_segment {
    local -n _content="${1:-}"
    local -n _hilite="${2:-false}"

    # if user is root, change the segment colors and prompt
    if [[ ${EUID} -eq 0 ]]; then
        _hilite=true
        _content=${PL_OPTIONS[prompt_symbol_root]}
    else
        _content=${PL_OPTIONS[prompt_symbol_normal]}
    fi
}
