#!/bin/env bash

# pwd_segment

# -----------------------------------------------------------------------------
# append to prompt: current directory
# arg: $1 foreground color
# arg; $2 background color
# option variables;
#   PL_PATH_TRIM: 0—fullpath, 1—current dir, [x]—trim to x number of dir
function pwd_segment {
    local bg_color="$1"
    local fg_color="$2"
    local content="${PWD/#$HOME/\~}" #$(pwd)
    if [[ $PL_PATH_TRIM -eq 1 ]]; then
        content="${content##*/}"
    elif [[ $PL_PATH_TRIM -gt 1 ]]; then
         local re=")$"
         local ree="\/[^\/]*"
         for (( i = 0; i < PL_PATH_TRIM; i++ ))
         do
             re="$ree$re"
         done
         re="($re"
         [[ $content =~ $re ]]
         ret=${BASH_REMATCH[1]}
         [[ ${#ret} -gt 0 ]] && content="$ret"
    fi
    local sep end_symbol
    pl_symbol sep 'soft_separator'
    content="${content//\// $sep }"
    [[ ${content:0:2} == " $sep" ]] && content="/$content"
    [[ ${content: -2} == "$sep " ]] && content=${content%%???}
    segment_end end_symbol "$fg_color" "$bg_color"
    segment_content content "$fg_color" "$bg_color"
    PS1+="$end_symbol $content "
    # shellcheck disable=SC2034
    __last_color="$bg_color"
}
