#!/usr/bin/env bash

# python_segment

PL_SYMBOLS['python']=${PL_SYMBOLS[python]:-'π'}

# -----------------------------------------------------------------------------
# segment content: python virtual environment name
# shellcheck disable=SC2034
function _python_segment {
    [[ -z ${VIRTUAL_ENV:-} ]] && return

    local -n _content="${1:-}"
    local venv="${VIRTUAL_ENV##*/}"
    _content="${PL_SYMBOLS[python]} ${venv}"
}

