#!/usr/bin/env bash
#
# screen_session_segmen

PL_SCREEN_SYMBOL='💻 '

# -----------------------------------------------------------------------------
# append to prompt: "screen" session name
# arg: $1 primary color
# arg; $2 secondary color
function screen_session_segment {
    if [[ ${TERM:-} == screen.* && -n ${STY:-} ]]; then
        local primary_color="$1"
        local secondary_color="$2"
        add_segment "${PL_SCREEN_SYMBOL}${STY}" "${primary_color}" "${secondary_color}"
    fi
}


