#!/bin/env bash
#
# screen_session_segmen

PL_SYMBOLS+=([screen]="💻")

# -----------------------------------------------------------------------------
# append to prompt: "screen" session name
# arg: $1 foreground color
# arg; $2 background color
function screen_session_segment {
    if [[ ${TERM} == screen.* && -n ${STY} ]]; then
        local bg_color="$1"
        local fg_color="$2"
        local screen_symbol
        pl_symbol screen_symbol 'screen'
        add_segment "${screen_symbol} ${STY}" "${fg_color}" "${bg_color}"
    fi
}


