#!/usr/bin/env bash
#
# screen_session_segmen

# shellcheck disable=SC2154
PL_OPTIONS[screen_symbol]=${PL_OPTIONS[screen_symbol]:-'💻'}

# -----------------------------------------------------------------------------
# segment content: "screen" session name
# shellcheck disable=SC2034
function _screen_segment {
    if [[ ${TERM:-} == screen.* && -n ${STY:-} ]]; then
        local -n _content="${1:-}"
        local -n _hilite="${2:-false}"
        _content="${PL_OPTIONS[screen_symbol]} ${STY}"
    fi
}


