#!/bin/env bash
#
# screen_session_segmen

PL_SYMBOLS+=(
    # GUI Font Symbols  # Standard Symbols for tty
    [screen]="💻"       [tty_screen]="■" 
)

# -----------------------------------------------------------------------------
# append to prompt: "screen" session name
# arg: $1 foreground color
# arg; $2 background color
function screen_session_segment {
    if [[ $TERM == screen.* && -n $STY ]]; then
        local bg_color="$1"
        local fg_color="$2"
        local content
        content=" $(pl_symbol 'screen') ${STY}"
        PS1+="$(segment_end "$fg_color" "$bg_color")"
        PS1+="$(segment_content "$fg_color" "$bg_color" "$content ")"
        # shellcheck disable=SC2034
        __last_color="$bg_color"
    fi
}


