#!/usr/bin/env bash
#
# time_segment

# -----------------------------------------------------------------------------
# append to prompt: current time
# optional variables;
#   PL_OPTIONS[time_show_seconds]: true/false for hh:mm:ss / hh:mm
# shellcheck disable=SC2034
function _time_segment {
    local -n _content="${1:-}"
    if ${PL_OPTIONS[time_show_seconds]:-false:} ; then
        _content="\t"
    else
        _content="\A"
    fi
}
