#!/bin/env bash

# virtual_env_segment

PL_SYMBOLS+=( [python]='π' )

# -----------------------------------------------------------------------------
# append to prompt: python virtual environment name
# arg: $1 foreground color
# arg; $2 background color
function virtual_env_segment {
    [[ -z ${VIRTUAL_ENV} ]] && return

    local venv="${VIRTUAL_ENV##*/}"
    local bg_color="$1"
    local fg_color="$2"
    local env_symbol
    pl_symbol env_symbol 'python'
    add_segment "${env_symbol} ${venv}" "${fg_color}" "${bg_color}"
}

